apiVersion: batch/v1
kind: Job
metadata:
  name: ping-pong-runc-job
spec:
  template:
    metadata:
      name: ping-pong-runc-client
      labels:
        name: ping-pong-runc
    spec:
      runtimeClassName: runc
      affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - ping-pong-runc
                topologyKey: kubernetes.io/hostname
      restartPolicy: OnFailure
      containers:
      - name: ping-pong-runc-client
        image: docker.io/sdeoras/ping-pong-client:85e47e08-clean
        imagePullPolicy: IfNotPresent
        command:
          - /ping-pong-client
        args:
          - run
          - --host
          - ping-pong-runc-server-service
          - --port
          - "5001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
