apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server-deployment
spec:
  selector:
    matchLabels:
      app: ping-pong-server
  template:
    metadata:
      labels:
        app: ping-pong-server
    spec:
      containers:
      - name: ping-pong-server
        image: ping-pong
        command:
          - /usr/local/bin/ping-pong-server
        args:
          - run
          - --host
          - 0.0.0.0
          - --port
          - "5001"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server-service
spec:
  type: ClusterIP
  selector:
    app: ping-pong-server
  ports:
  - port: 5001
    targetPort: 5001

