apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-kata-server-deployment
spec:
  selector:
    matchLabels:
      app: ping-pong-kata-server
  template:
    metadata:
      name: ping-pong-kata-server
      labels:
        app: ping-pong-kata-server
        name: ping-pong-kata
    spec:
      runtimeClassName: kata-runtime
      containers:
      - name: ping-pong-kata-server
        image: docker.io/sdeoras/ping-pong-server:85e47e08-clean
        command:
          - /ping-pong-server
        args:
          - run
          - --host
          - 0.0.0.0
          - --port
          - "5001"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-kata-server-service
spec:
  type: ClusterIP
  selector:
    app: ping-pong-kata-server
  ports:
  - port: 5001
    targetPort: 5001

